import json
import yaml
from pydantic_settings import BaseSettings
from pydantic import Field

class GenieConfig(BaseSettings):
    planner_system_prompt_dict: dict = Field(default={}, validation_alias="autobots.autoagent.planner.system_prompt")
    planner_next_step_prompt_dict: dict = Field(default={}, validation_alias="autobots.autoagent.planner.next_step_prompt")
    executor_system_prompt_dict: dict = Field(default={}, validation_alias="autobots.autoagent.executor.system_prompt")
    executor_next_step_prompt_dict: dict = Field(default={}, validation_alias="autobots.autoagent.executor.next_step_prompt")
    executor_sop_prompt_dict: dict = Field(default={}, validation_alias="autobots.autoagent.executor.sop_prompt")
    react_system_prompt_dict: dict = Field(default={}, validation_alias="autobots.autoagent.react.system_prompt")
    react_next_step_prompt_dict: dict = Field(default={}, validation_alias="autobots.autoagent.react.next_step_prompt")
    planner_model_name: str = Field(default="gpt-4o-0806", validation_alias="autobots.autoagent.planner.model_name")
    executor_model_name: str = Field(default="gpt-4o-0806", validation_alias="autobots.autoagent.executor.model_name")
    react_model_name: str = Field(default="gpt-4o-0806", validation_alias="autobots.autoagent.react.model_name")
    plan_tool_desc: str = Field(default="", validation_alias="autobots.autoagent.tool.plan_tool.desc")
    code_agent_desc: str = Field(default="", validation_alias="autobots.autoagent.tool.code_agent.desc")
    report_tool_desc: str = Field(default="", validation_alias="autobots.autoagent.tool.report_tool.desc")
    knowledge_tool_desc: str = Field(default="", validation_alias="autobots.autoagent.tool.knowledge_tool.desc")
    multi_modal_agent_desc: str = Field(default="", validation_alias="autobots.autoagent.tool.multimodalagent_tool.desc")
    file_tool_desc: str = Field(default="", validation_alias="autobots.autoagent.tool.file_tool.desc")
    deep_search_tool_desc: str = Field(default="", validation_alias="autobots.autoagent.tool.deep_search_tool.desc")
    data_analysis_tool_desc: str = Field(default="", validation_alias="autobots.autoagent.tool.data_analysis_tool.desc")
    plan_tool_params: dict = Field(default={}, validation_alias="autobots.autoagent.tool.plan_tool.params")
    code_agent_params: dict = Field(default={}, validation_alias="autobots.autoagent.tool.code_agent.params")
    report_tool_params: dict = Field(default={}, validation_alias="autobots.autoagent.tool.report_tool.params")
    knowledge_tool_params: dict = Field(default={}, validation_alias="autobots.autoagent.tool.knowledge_tool.params")
    multi_modal_agent_params: dict = Field(default={}, validation_alias="autobots.autoagent.tool.multimodalagent_tool.params")
    file_tool_params: dict = Field(default={}, validation_alias="autobots.autoagent.tool.file_tool.params")
    deep_search_params: dict = Field(default={}, validation_alias="autobots.autoagent.tool.deep_search.params")
    data_analysis_tool_params: dict = Field(default={}, validation_alias="autobots.autoagent.tool.data_analysis_tool.params")
    file_tool_content_truncate_len: int = Field(default=5000, validation_alias="autobots.autoagent.tool.file_tool.truncate_len")
    deep_search_tool_file_desc_truncate_len: int = Field(default=500, validation_alias="autobots.autoagent.tool.deep_search.file_desc.truncate_len")
    deep_search_tool_message_truncate_len: int = Field(default=500, validation_alias="autobots.autoagent.tool.deep_search.message.truncate_len")
    plan_pre_prompt: str = Field(default="分析问题并制定计划：", validation_alias="autobots.autoagent.planner.pre_prompt")
    task_pre_prompt: str = Field(default="参考对话历史回答，", validation_alias="autobots.autoagent.task.pre_prompt")
    clear_tool_message: str = Field(default="1", validation_alias="autobots.autoagent.tool.clear_tool_message")
    planning_close_update: str = Field(default="1", validation_alias="autobots.autoagent.planner.close_update")
    deep_search_page_count: str = Field(default="5", validation_alias="autobots.autoagent.deep_search_page_count")
    multi_agent_tool_list_dict: dict = Field(default={}, validation_alias="autobots.autoagent.tool_list")
    llm_settings_dict: dict = Field(default={}, validation_alias="llm.settings")
    planner_max_steps: int = Field(default=40, validation_alias="autobots.autoagent.planner.max_steps")
    executor_max_steps: int = Field(default=40, validation_alias="autobots.autoagent.executor.max_steps")
    react_max_steps: int = Field(default=40, validation_alias="autobots.autoagent.react.max_steps")
    max_observe: str = Field(default=10000, validation_alias="autobots.autoagent.executor.max_observe")
    code_interpreter_url: str = Field(default="", validation_alias="autobots.autoagent.code_interpreter_url")
    deep_search_url: str = Field(default="", validation_alias="autobots.autoagent.deep_search_url")
    mcp_client_url: str = Field(default="", validation_alias="autobots.autoagent.mcp_client_url")
    mcp_server_url_arr: list = Field(default=[], validation_alias="autobots.autoagent.mcp_server_url")
    auto_bots_knowledge_url: str = Field(default="", validation_alias="autobots.autoagent.knowledge_url")
    multi_modal_agent_url: str = Field(default="", validation_alias="autobots.autoagent.multimodalagent_url")
    data_analysis_url: str = Field(default="", validation_alias="autobots.autoagent.data_analysis_url")
    summary_system_prompt: str = Field(default="", validation_alias="autobots.autoagent.summary.system_prompt")
    digital_employee_prompt: str = Field(default="", validation_alias="autobots.autoagent.digital_employee_prompt")
    message_size_limit: int = Field(default=10000, validation_alias="autobots.autoagent.summary.message_size_limit")
    sensitive_patterns: dict = Field(default={}, validation_alias="autobots.autoagent.sensitive_patterns")
    output_style_prompts_dict: dict = Field(default={}, validation_alias="autobots.autoagent.output_style_prompts")
    message_interval: dict = Field(default={}, validation_alias="autobots.autoagent.message_interval")
    struct_parse_tool_system_prompt: str = Field(default={}, validation_alias="autobots.autoagent.struct_parse_tool_system_prompt")
    sse_client_read_timeout: int = Field(default=1800, validation_alias="autobots.multiagent.sseClient.readTimeout")
    sse_client_connect_timeout: int = Field(default=1800, validation_alias="autobots.multiagent.sseClient.connectTimeout")
    genie_sop_prompt: str = Field(default="", validation_alias="autobots.autoagent.genie_sop_prompt")
    genie_base_prompt: str = Field(default="", validation_alias="autobots.autoagent.genie_base_prompt")
    task_complete_desc: str = Field(default="当前task完成，请将当前task标记为 completed", validation_alias="autobots.autoagent.tool.task_complete_desc")


genie_config = GenieConfig()
